default_interpreter_label: 'Python 3.11.12 (conda: remdis)'
default_interpreter_path: /Users/fujie/anaconda3/envs/remdis/bin/python
default_workdir: /Users/fujie/work/2025/remdis/modules
launchers:
- config:
    cmdline: docker run -i --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.12-management
    workdir: /Users/fujie/work/2025/remdis/modules
  geometry:
  - 0
  - 0
  - 403
  - 484
  type: shell
- config:
    interpreter: /Users/fujie/anaconda3/envs/remdis/bin/python
    script: /Users/fujie/work/2025/remdis/modules/text_vap.py
    workdir: /Users/fujie/work/2025/remdis/modules
  geometry:
  - 806
  - 0
  - 904
  - 578
  type: python
- config:
    interpreter: /Users/fujie/anaconda3/envs/remdis/bin/python
    script: /Users/fujie/work/2025/remdis/modules/dialogue.py
    workdir: /Users/fujie/work/2025/remdis/modules
  geometry:
  - 807
  - 577
  - 903
  - 444
  type: python
- config:
    interpreter: /Users/fujie/anaconda3/envs/remdis/bin/python
    script: /Users/fujie/work/2025/remdis/modules/asr.py
    workdir: /Users/fujie/work/2025/remdis/modules
  geometry:
  - 402
  - 308
  - 406
  - 390
  type: python
- config:
    interpreter: /Users/fujie/anaconda3/envs/remdis/bin/python
    script: /Users/fujie/work/2025/remdis/modules/input.py
    workdir: /Users/fujie/work/2025/remdis/modules
  geometry:
  - 402
  - 0
  - 406
  - 309
  type: python
- config:
    cmdline: ../../MMDAgent-EX/Release/MMDAgent-EX main.mdf
    workdir: /Users/fujie/work/2025/remdis/MMDAgent-EX
  geometry:
  - 0
  - 483
  - 403
  - 514
  type: shell
- config:
    interpreter: /Users/fujie/anaconda3/envs/remdis/bin/python
    script: /Users/fujie/work/2025/remdis/modules/tts.py
    workdir: /Users/fujie/work/2025/remdis/modules
  geometry:
  - 402
  - 697
  - 406
  - 300
  type: python
mainwindow_geometry:
- 0
- 72
- 1710
- 996
mainwindow_maximized: true
